global:
  checkNewVersion: false
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

providers:
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: false

api:
  dashboard: false
  insecure: true

entryPoints:
  web:
    address: ':9999'
    http2:
      maxConcurrentStreams: 125

# log:
#   level: WARN  # ERROR, DEBUG, PANIC, FATAL, ERROR, WARN, INFO